---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.IssueTracking

components: 
  schemas: 
    Open311_ServiceType: 
      $ref: "https://smart-data-models.github.io/dataModel.IssueTracking/Open311_ServiceType/model.yaml#/Open311_ServiceType"
info: 
  description: |
    As per Open311 an entity of type ServiceType is an acceptable 311 service
    request type. A request type can be unique to the city/jurisdiction.
  title: Open311_ServiceType
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Open311_ServiceType
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.IssueTracking/Open311_ServiceType/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.IssueTracking/Open311_ServiceType/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
